
name: build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        node-version: [16.x]
        os: [macos-12, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run package
    - name: 'upload macos artifact'
      uses: actions/upload-artifact@v3.1.1
      with:
        name: macos
        path: ./release/build/*.dmg
    - name: 'upload windows artifact'
      uses: actions/upload-artifact@v3.1.1
      with:
        name: windows
        path: ./release/build/*.exe
