
name: build_pr

on:
  pull_request:
    branches: [ "main" ]


jobs:
  build_pr:
    strategy:
      matrix:
        node-version: [16.x]
        os: [macos-12, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run package
